spring.application.name=ComplyEase
spring.datasource.url=jdbc:mysql://localhost:3306/complyease
spring.datasource.username=root
spring.datasource.password=$H@bbir0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true